apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nagendrappa/jenkins-argocd-gitops.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://38F3FD1A5BCD668B3CA927675C338DCA.gr7.us-east-1.eks.amazonaws.com
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true